version: "3.9"

services:
    backend-service:
        build: ./src/backend/
        ports:
            - "5000:5000"
        volumes: 
            - ./src/backend/:/app
        
    frontend-service:
        build: ./src/frontend/
        ports:
            - "80:80"
        volumes: 
            - ./src/frontend/:/usr/share/nginx/html